version: "3"

services:
  plex:
    container_name: plex-container
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: ${MVD_TIMEZONE}
      PLEX_CLAIM: ${MVD_PMS_CLAIM_TOKEN}
      ADVERTISE_IP: ${MVD_PMS_SERV_IP}
    hostname: ${MVD_PMS_HOSTNAME}
    volumes:
      - ${MVD_PMS_VOL_FOLDER}/config:/config
      - ${MVD_PMS_VOL_FOLDER}/transcode:/transcode
      - ${MVD_PMS_VOL_FOLDER}/data:/data
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr-container
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      TZ: ${MVD_TIMEZONE}
    volumes:
      - ${MVD_RDR_VOL_FOLDER}/config:/config
      - ${MVD_RDR_VOL_FOLDER}/movies:/movies
      - ${MVD_RDR_VOL_FOLDER}/downloads:/downloads

  jackett:
    container_name: jackett-container
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      TZ: ${MVD_TIMEZONE}
      AUTO_UPDATE: "true"
    volumes:
      - ${MVD_JKT_VOL_FOLDER}/config:/config
      - ${MVD_JKT_VOL_FOLDER}/downloads:/downloads
  
  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr-container
    restart: unless-stopped
    ports:
      - 8191:8191
    environment:
      TZ: ${MVD_TIMEZONE}